name: Persona
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+5 # Dependency for picking images from the gallery
  file_picker: ^5.0.1 # Cross-platform file picker for better compatibility
  cupertino_icons: ^1.0.6 # Dependency for Cupertino icons
  http: ^0.13.4
  go_router: ^14.6.2
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  flutter_launcher_icons: ^0.14.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Linting package for improved code quality

flutter:
  uses-material-design: true

  assets:
      - assets/images/
      - assets/animations/face-scan.json
    # - assets/images/Frame-2.png
    # - assets/images/img-onb1.png
    # - assets/images/img-onb2.png
    # - assets/images/img-onb3.png
    # - assets/images/img-main1.png
    # - assets/images/profile.png
    # - assets/images/jessica.png
    # - assets/images/hairstyle.png
    # - assets/images/glasses.png
    # - assets/images/accessorry.png
    # - assets/images/card1.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png" # Set the foreground image (same or different from image_path)
  adaptive_icon_background: "#ffffff" # Set the background color of the adaptive icon
  min_sdk_android: 21
  android_require_shape: true